[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  command = "npm start"
  port = 3001

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
